In [1]:
alphabets = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

In [3]:
list(enumerate(alphabets))

[(0, 'A'),
 (1, 'B'),
 (2, 'C'),
 (3, 'D'),
 (4, 'E'),
 (5, 'F'),
 (6, 'G'),
 (7, 'H'),
 (8, 'I'),
 (9, 'J'),
 (10, 'K'),
 (11, 'L'),
 (12, 'M'),
 (13, 'N'),
 (14, 'O'),
 (15, 'P'),
 (16, 'Q'),
 (17, 'R'),
 (18, 'S'),
 (19, 'T'),
 (20, 'U'),
 (21, 'V'),
 (22, 'W'),
 (23, 'X'),
 (24, 'Y'),
 (25, 'Z')]

In [4]:
dict(list(enumerate(alphabets)))

{0: 'A',
 1: 'B',
 2: 'C',
 3: 'D',
 4: 'E',
 5: 'F',
 6: 'G',
 7: 'H',
 8: 'I',
 9: 'J',
 10: 'K',
 11: 'L',
 12: 'M',
 13: 'N',
 14: 'O',
 15: 'P',
 16: 'Q',
 17: 'R',
 18: 'S',
 19: 'T',
 20: 'U',
 21: 'V',
 22: 'W',
 23: 'X',
 24: 'Y',
 25: 'Z'}

In [5]:
int_to_char = dict(list(enumerate(alphabets)))

In [7]:
int_to_char[6]

'G'

In [12]:
dict((v, i) for i, v in enumerate(alphabets))

{'A': 0,
 'B': 1,
 'C': 2,
 'D': 3,
 'E': 4,
 'F': 5,
 'G': 6,
 'H': 7,
 'I': 8,
 'J': 9,
 'K': 10,
 'L': 11,
 'M': 12,
 'N': 13,
 'O': 14,
 'P': 15,
 'Q': 16,
 'R': 17,
 'S': 18,
 'T': 19,
 'U': 20,
 'V': 21,
 'W': 22,
 'X': 23,
 'Y': 24,
 'Z': 25}

In [13]:
char_to_int = dict((v, i) for i, v in enumerate(alphabets))

In [14]:
char_to_int['X']

23

#### Prepare the dataset

In [18]:
seq_length = 1
x = []
y = []

for i in range(len(alphabets) - seq_length):
    seq_in = [alphabets[i]]
    seq_out = alphabets[i+1] 
    print(seq_in,'-->',seq_out)   
    x += [[char_to_int[seq_in[0]]]]
    y += [char_to_int[seq_out]]

['A'] --> B
['B'] --> C
['C'] --> D
['D'] --> E
['E'] --> F
['F'] --> G
['G'] --> H
['H'] --> I
['I'] --> J
['J'] --> K
['K'] --> L
['L'] --> M
['M'] --> N
['N'] --> O
['O'] --> P
['P'] --> Q
['Q'] --> R
['R'] --> S
['S'] --> T
['T'] --> U
['U'] --> V
['V'] --> W
['W'] --> X
['X'] --> Y
['Y'] --> Z


In [19]:
x

[[0],
 [1],
 [2],
 [3],
 [4],
 [5],
 [6],
 [7],
 [8],
 [9],
 [10],
 [11],
 [12],
 [13],
 [14],
 [15],
 [16],
 [17],
 [18],
 [19],
 [20],
 [21],
 [22],
 [23],
 [24]]

In [20]:
y

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25]

In [21]:
import numpy as np

In [23]:
x = np.reshape(x, (25, 1, 1))

In [24]:
x

array([[[ 0]],

       [[ 1]],

       [[ 2]],

       [[ 3]],

       [[ 4]],

       [[ 5]],

       [[ 6]],

       [[ 7]],

       [[ 8]],

       [[ 9]],

       [[10]],

       [[11]],

       [[12]],

       [[13]],

       [[14]],

       [[15]],

       [[16]],

       [[17]],

       [[18]],

       [[19]],

       [[20]],

       [[21]],

       [[22]],

       [[23]],

       [[24]]])

In [25]:
x_norm = x / 25

In [26]:
x_norm

array([[[0.  ]],

       [[0.04]],

       [[0.08]],

       [[0.12]],

       [[0.16]],

       [[0.2 ]],

       [[0.24]],

       [[0.28]],

       [[0.32]],

       [[0.36]],

       [[0.4 ]],

       [[0.44]],

       [[0.48]],

       [[0.52]],

       [[0.56]],

       [[0.6 ]],

       [[0.64]],

       [[0.68]],

       [[0.72]],

       [[0.76]],

       [[0.8 ]],

       [[0.84]],

       [[0.88]],

       [[0.92]],

       [[0.96]]])

In [27]:
y

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25]

In [28]:
from keras.utils import to_categorical

In [29]:
a = [1,3,2,3,2,1,1,2,3]

In [30]:
to_categorical(a)

array([[0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
y_new = to_categorical(y)

In [32]:
y_new

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 

In [33]:
y_new.shape

(25, 26)

In [34]:
x_norm.shape

(25, 1, 1)

#### Build the model

In [37]:
from keras.layers import SimpleRNN, Dense, Input
from keras.models import Sequential

In [39]:
model = Sequential()

model.add(Input((1,1)))
model.add(Dense(25, activation='relu'))
model.add(SimpleRNN(32))
model.add(Dense(26, activation='softmax'))

In [40]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 1, 25)          │            50 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_1 (SimpleRNN)        │ (None, 32)             │         1,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 26)             │           858 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,764 (10.80 KB)

 Trainable params: 2,764 (10.80 KB)

 Non-trainable params: 0 (0.00 B)

#### Compile the model

In [43]:
model.compile(loss='categorical_crossentropy', 
              optimizer='adam',metrics= ['accuracy'])

#### Train the model

In [46]:
model.fit(x_norm, y_new, epochs=500, batch_size=1)

Epoch 1/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7853 - loss: 1.1598
Epoch 2/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8286 - loss: 1.2113
Epoch 3/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8507 - loss: 1.1726
Epoch 4/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7643 - loss: 1.1672   
Epoch 5/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6436 - loss: 1.2864
Epoch 6/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8318 - loss: 1.2951
Epoch 7/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9716 - loss: 1.2361
Epoch 8/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8083 - loss: 1.2606
Epoch 9/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8859 - loss: 1.1715
Epoch 10/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9000 - loss: 1.2396
Epoch 11/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6778 - loss: 1.2410   
Epoch 12/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc

In [47]:
model.evaluate(x_norm, y_new, batch_size=1)

25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9953 - loss: 0.5566  


[0.6721782684326172, 0.9599999785423279]

In [49]:
new = 'M'
new = char_to_int[new]
new = np.reshape(new,(1,1,1))
new = new / 25
pred = model.predict(new, verbose=False)
pred = np.argmax(pred)
int_to_char[pred]

'N'

In [52]:
seq_length = 3
x = []
y = []

for i in range(len(alphabets) - seq_length):
    seq_in = alphabets[i:i+seq_length]
    seq_out = alphabets[i+seq_length] 
    print(seq_in,'-->',seq_out)   
    x.append([char_to_int[char] for char in seq_in])
    y += [char_to_int[seq_out]]

ABC --> D
BCD --> E
CDE --> F
DEF --> G
EFG --> H
FGH --> I
GHI --> J
HIJ --> K
IJK --> L
JKL --> M
KLM --> N
LMN --> O
MNO --> P
NOP --> Q
OPQ --> R
PQR --> S
QRS --> T
RST --> U
STU --> V
TUV --> W
UVW --> X
VWX --> Y
WXY --> Z


In [53]:
x_new = np.reshape(x, (23, seq_length, 1))

In [54]:
y_new = to_categorical(y)
y_new.shape

(23, 26)

In [55]:
x_new = x_new / 25

In [61]:
x_new;

In [57]:
model = Sequential()

model.add(Input((3,1)))
model.add(Dense(25, activation='relu'))
model.add(SimpleRNN(32))
model.add(Dense(26, activation='softmax'))

In [58]:
model.compile(loss='categorical_crossentropy', optimizer='adam',
             metrics=['accuracy'])

In [59]:
model.fit(x_new, y_new, epochs=1000, batch_size=1)

Epoch 1/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.0000e+00 - loss: 3.3738
Epoch 2/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0316 - loss: 3.3062   
Epoch 3/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0118 - loss: 3.2918    
Epoch 4/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0281 - loss: 3.2130   
Epoch 5/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0553 - loss: 3.1680 
Epoch 6/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0219 - loss: 3.1921    
Epoch 7/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0494 - loss: 3.0860   
Epoch 8/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0471 - loss: 3.0289   
Epoch 9/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0995 - loss: 3.0169   
Epoch 10/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0535 - loss: 2.9469   
Epoch 11/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0545 - loss: 2.8640   
Epoch 12/1000
23/2

In [62]:
new = 'JKL'
val = np.array([[char_to_int[x]] for x in new])
val = val.reshape(1,3,1)
val = val / 25
result = model.predict(val, verbose=False)
result = np.argmax(result)
print(new,'-->',int_to_char[result])

JKL --> M
